### ISSUE TITLE
Add editing to validate exchange

### ISSUE THREAD

**Issue by ny4i** [mbridak/WinterFieldDayLogger#23]
I work on another logger but I like the idea of doing this in PyQT. I stumbled upon this after WFD but I did have an idea I wonder if you would entertain as a pull request.

Specifically, I noticed that I could log 1A CTA in Winter Field Day. That is not a valid class for Winter (I, O, H or M) nor is it a valid section. I would like to add some editing and an alert to the user that the class and section are wrong. This makes after the contest cleanup easier. Is that something that would be useful?

Tom NY4I

**Comment by mbridak** [comment]
Sounds like a good idea. I've created a branch for it.

We could evaluate the class/section as the user types in the field, turning the text green if valid and red if not. If the user presses ENTER to submit the contact we could have an optional settings flag to display a verification dialog to the user to submit it anyways.

I'd want to be sure to keep the control in the users hands.

**Comment by mbridak** [comment]
Made some progress.

![image](https://user-images.githubusercontent.com/49108421/216746516-bfefa22a-763f-49e6-90a7-5e9590b1c926.png)

This showing two valid entries.

![image](https://user-images.githubusercontent.com/49108421/216746576-edc1d109-2c37-4a8d-8a5e-207321d03693.png)

This showing two invalid entries.

I think we can forgo the dialog. Since I believe the visual cues work well enough.
